[package]
name = "evm-disasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.63"
hex = "0.4.3"
nom = "7.1.1"
nom_locate = "4.0.0"
num-bigint = "0.4.3"
num256 = "0.3.5"
